FROM golang:1.22-bookworm AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0

WORKDIR /build

COPY . .

RUN go mod download

RUN make worker

FROM continuumio/miniconda3:24.5.0-0 AS app

RUN conda install conda-forge::vapoursynth=69 -y
RUN conda install tongyuantongyu::vapoursynth-bestsource=5 -y

WORKDIR /app

COPY --from=builder /build/worker/worker /app/
COPY --from=builder /build/conf/finalrip.yml /app/conf/

CMD ["/app/worker", "encode"]
